data:

dataset: 
    name: cifar
    image_size: 32
    in_channels: 3
    out_channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 8

model:
    hidden_channels: 128
    channel_factor: [1, 2, 4]
    num_res_blocks: 2
    apply_attention_resolutions: [16,]
    dropout: 0.0
    var_type: fixedsmall
    ema_rate: 0.999
    ema: True
    # resamp_with_conv: True 

diffusion:
    beta_schedule: linear
    beta_start: 0.1
    beta_end: 20
    sigma_start: 0.01
    sigma_end: 0.5
    num_diffusion_timesteps: 1000
    sde_dynamics: VPSDE 


sampling:
    batch_size: 8
    last_only: True
    sampler: 'reverse_vpsde'
    visualization: 'discretize'


training: 
    batch_size: 64
    lr: 0.001
    num_epochs: 200
    grad_clip: 2.   # clipping gradients. 
    use_grad_clip: false
    reduce_mean: false
    loss: 'discrete'
    display_freq: 500